FROM alpine:latest

ARG TARGETPLATFORM
#ARG BUILDPLATFORM

# App Path
ARG APP_PATH="/opt/app"


# Skopeo tag
#ARG SKOPEO_TAG="v1.15"
ARG SKOPEO_TAG="latest"

# RegClient tag
#ARG REGCLIENT_TAG="v0.6.0"
ARG REGCLIENT_TAG="latest"

# Crane tag
#ARG CRANE_TAG="v0.19.1"
ARG CRANE_TAG="latest"



# Create Directory for App
RUN mkdir -p "/opt"
RUN mkdir -p "${APP_PATH}"

# Change Directory
WORKDIR "${APP_PATH}"

# Copy Sources
COPY app/ "${APP_PATH}"

# Update Sources
RUN apk update

# Install other Dependencies / recommended Packages
# Shadow is needed in order to use "chsh"
RUN apk add --no-cache ca-certificates bash curl wget shadow

# Install skopeo
# Not needed anymore when using Binary Packages from https://github.com/lework/skopeo-binary/releases
# RUN apk add --no-cache skopeo 

# Install podman
# Needed when using Binary Packages from https://github.com/lework/skopeo-binary/releases since podman would be normally be pulled in together with skopeo
RUN apk add --no-cache podman

# Change Shell
RUN chsh -s /bin/bash root
RUN export SHELL="/bin/bash"
RUN ln -sf /bin/bash /bin/sh

# set ENV to execute startup scripts
ENV ENV /etc/profile

# Set PATH Variable
ENV PATH="${APP_PATH}:$PATH"



# Copy Regclient Installer Script
COPY install-regclient.sh /opt/install-regclient.sh

# RUN Regclient Installer Script
RUN bash -c /opt/install-regclient.sh "${TARGETPLATFORM}" "${REGCLIENT_TAG}"

# Set Path to include RegClient
ENV PATH="/opt/regclient:$PATH"



# Copy Skopeo Installer Script
COPY install-skopeo.sh /opt/install-skopeo.sh

# RUN Skopeo Installer Script
RUN bash -c /opt/install-skopeo.sh "${TARGETPLATFORM}" "${SKOPEO_TAG}"

# Set Path to include Skopeo
ENV PATH="/opt/skopeo:$PATH"



# Copy Crane Installer Script
COPY install-crane.sh /opt/install-crane.sh

# RUN Regclient Installer Script
RUN bash -c /opt/install-crane.sh "${TARGETPLATFORM}" "${CRANE_TAG}"

# Set Path to include Crane
ENV PATH="/opt/crane:$PATH"



# Copy and Execute Entrypoint Script
COPY docker-entrypoint.sh /opt/
RUN chmod +x /opt/docker-entrypoint.sh
ENTRYPOINT ["/opt/docker-entrypoint.sh"]
