FROM debian:latest

ARG TARGETPLATFORM
#ARG BUILDPLATFORM

# App Path
ARG APP_PATH="/opt/app"

# RegClient tag
#ARG REGCLIENT_TAG="v0.6.0"
ARG REGCLIENT_TAG="latest"

# Crane tag
#ARG CRANE_TAG="v0.19.1"
ARG CRANE_TAG="latest"


# Create Directory for App
RUN mkdir -p "/opt"
RUN mkdir -p "${APP_PATH}"

# Change Directory
WORKDIR "${APP_PATH}"

# Copy Sources
COPY app/ "${APP_PATH}"

# Change Directory
WORKDIR "/etc"

# Add APT Configuration for more recent (testing) Packages
ADD etc /etc/

# Change Workdir Back to App Folder
WORKDIR "${APP_PATH}"


# Update Sources
RUN apt-get update

# Install other Dependencies / recommended Packages
RUN apt-get install -y ca-certificates bash curl wget

# Install skopeo
RUN apt-get install -y skopeo 

# Clean APT Cache
RUN apt-get clean

# Change Shell
RUN chsh -s /bin/bash root
RUN export SHELL="/bin/bash"
RUN ln -sf /bin/bash /bin/sh

# set ENV to execute startup scripts
ENV ENV /etc/profile

# Set PATH Variable
ENV PATH="${APP_PATH}:$PATH"



# Copy Regclient Installer Script
COPY install-regclient.sh /opt/install-regclient.sh

# RUN Regclient Installer Script
RUN bash -c /opt/install-regclient.sh "${TARGETPLATFORM}" "${REGCLIENT_TAG}"

# Set Path to include RegClient
ENV PATH="/opt/regclient:$PATH"



# Copy Crane Installer Script
COPY install-crane.sh /opt/install-crane.sh

# RUN Regclient Installer Script
RUN bash -c /opt/install-crane.sh "${TARGETPLATFORM}" "${CRANE_TAG}"

# Set Path to include Crane
ENV PATH="/opt/crane:$PATH"



# Copy and Execute Entrypoint Script
COPY docker-entrypoint.sh /opt/
RUN chmod +x /opt/docker-entrypoint.sh
ENTRYPOINT ["/opt/docker-entrypoint.sh"]
